name: release

on:
  push:
    branches: [ main ]

env:
  SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
  SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run tests
        run: NO_PUBLISH=true gradle test

  qa:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run qa checks
        run: NO_PUBLISH=true gradle pmdMain

  publish-to-sonatype:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Publish artifact to public Sonatype Nexus
        run: |
          echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
          gradle sign -x check publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository -Psonatype=true \
            -PossrhUsername=$SONATYPE_USERNAME \
            -PossrhPassword=$SONATYPE_PASSWORD \
            -Psigning.keyId=$SIGNING_KEYID  \
            -Psigning.password=$SIGNING_PASSWORD \
            -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg

